# -----------------------------------------------------------------------------
# WARNING: This file was auto-generated by dev-setup/setup.py. 
# Do not edit directly; modify the template or input variables instead.
# -----------------------------------------------------------------------------

#!/bin/bash
set -e


if [ -f "/opt/ros/humble/setup.bash" ]; then
    source "/opt/ros/humble/setup.bash"
fi
if [ -f "/workspace/install/setup.bash" ]; then
    source "/workspace/install/setup.bash"
fi

# Execute the passed command
exec "$@"